# CodeBook
This CodeBook describes all the variables used on this project.

# Dataset will be used:
'README.txt'

'features_info.txt': Shows information about the variables used on the feature vector.

'features.txt': List of all features.

'activity_labels.txt': Match code with their activity names.

'train/X_train.txt': Training set.

'train/y_train.txt': Training labels.

'test/X_test.txt': Test set.

'test/y_test.txt': Test labels.

'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.

# run_analysis.R Variables
'x_train': X_train.txt read into R.

'y_train': y_train.txt read into R. It contains the activity code classified on 'activity_labels.txt'

'subject_train':'subject_train.txt' read into R. it contains the subjects ids

'features': features.txt read into R.

'Merged_Data': primary data_frame containing the merged train and test data, arranged by subject.

'FinalData': tidy data frame with the averages resulted from step 5.
